In [1]:
import os
import sys
import json
import numpy as np

In [2]:
import sys
sys.path.append( "IDyOM" ) 

In [4]:
from idyom import idyom
from idyom import data

In [16]:
data_path = "data/(dis)similarities-22/MIDI_files/FS_MIDI/FS_MIDI_ROMANIA"

data_from_regionA = data.data()
data_from_regionA.parse( data_path )


________ We are working on 'data/(dis)similarities-22/MIDI_files/FS_MIDI/FS_MIDI_ROMANIA'

_____ Filling the database ...

 - data/(dis)similarities-22/MIDI_files/FS_MIDI/FS_MIDI_ROMANIA/romani01.mid
 - data/(dis)similarities-22/MIDI_files/FS_MIDI/FS_MIDI_ROMANIA/romani14.mid
 - data/(dis)similarities-22/MIDI_files/FS_MIDI/FS_MIDI_ROMANIA/romani28.mid
 - data/(dis)similarities-22/MIDI_files/FS_MIDI/FS_MIDI_ROMANIA/romani02.mid
 - data/(dis)similarities-22/MIDI_files/FS_MIDI/FS_MIDI_ROMANIA/romani16.mid
 - data/(dis)similarities-22/MIDI_files/FS_MIDI/FS_MIDI_ROMANIA/romani17.mid
 - data/(dis)similarities-22/MIDI_files/FS_MIDI/FS_MIDI_ROMANIA/romani03.mid
 - data/(dis)similarities-22/MIDI_files/FS_MIDI/FS_MIDI_ROMANIA/romani07.mid
 - data/(dis)similarities-22/MIDI_files/FS_MIDI/FS_MIDI_ROMANIA/romani13.mid
 - data/(dis)similarities-22/MIDI_files/FS_MIDI/FS_MIDI_ROMANIA/romani12.mid
 - data/(dis)similarities-22/MIDI_files/FS_MIDI/FS_MIDI_ROMANIA/romani06.mid
 - data/(dis)similarities-22/

['__class__',
 '__delattr__',
 '__dict__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getstate__',
 '__gt__',
 '__hash__',
 '__init__',
 '__init_subclass__',
 '__le__',
 '__lt__',
 '__module__',
 '__ne__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__setattr__',
 '__sizeof__',
 '__str__',
 '__subclasshook__',
 '__weakref__',
 'addFile',
 'addFiles',
 'addScore',
 'augmentByTransposition',
 'augmentData',
 'augmentRythm',
 'availableViewPoints',
 'data',
 'dataToViewpoint',
 'deleteDuplicates',
 'folderPath',
 'getData',
 'getNote',
 'getScore',
 'getScoresFeatures',
 'getSize',
 'getSizeofPiece',
 'getViewpointRepresentation',
 'load',
 'parse',
 'parseFile',
 'plotScores',
 'print',
 'quantization',
 'save',
 'viewpoints']

In [64]:
model = idyom.idyom(maxOrder=20, viewPoints=['pitch', 'length'])
model.train(data_from_regionA)

In [66]:
test_file = "data/(dis)similarities-22/MIDI_files/FS_MIDI/FS_MIDI_POLAND/polska01.mid"

In [68]:
surprise_values_pl = model.getSurprisefromFile( test_file )

In [69]:
surprise_values_pl

(array([3.89715159, 4.10999357, 3.45170359, 3.51392551, 3.77803317,
        4.16362047, 4.99934425, 7.68859566, 3.48753081, 5.38720676,
        2.07122595, 2.73848441, 2.99019008, 1.99148371, 4.25186196,
        1.29684605, 4.96373672, 3.46980564, 3.46637436, 3.4416951 ,
        3.21538547, 4.16645502, 6.38846649, 3.04364661, 5.92318002,
        2.06809265, 5.97680828, 5.01127501, 5.69026196, 2.70483199,
        5.28059921, 4.56643694, 3.37481825, 2.53861065, 3.4723346 ,
        2.94297179, 2.40934927, 1.92181513, 0.75062114, 2.01924587,
        2.57124778, 1.0331074 , 2.20681547, 1.45965863, 2.42077554,
        0.99865405, 1.29139051, 0.60732242, 7.78157534, 3.30129827]),
 array([4.5503081 , 4.36596021, 3.75117333, 3.52221337, 3.08360771,
        2.46997407, 3.10626065, 2.8716067 , 4.07709967, 2.88151439,
        1.68642006, 2.19783466, 1.53101133, 1.8989263 , 1.33210366,
        0.9812191 , 1.15396053, 3.35785528, 3.92734443, 3.46006412,
        3.36550648, 3.08358207, 3.23521802, 3.

In [79]:
surprise_values_pl[0].mean(), surprise_values_pl[1].mean()

(3.445917222056697, 2.5280190706328938)

In [80]:
test_file = "data/(dis)similarities-22/MIDI_files/FS_MIDI/FS_MIDI_CROATIA/Rasti_rozmarin_FS_HR.mid"

In [81]:
surprise_values_hr = model.getSurprisefromFile( test_file )

In [82]:
surprise_values_hr[0].mean(), surprise_values_hr[1].mean()

(4.433875024639217, 3.107185863950832)

In [85]:
surprise_vals_pl_folder = model.getSurprisefromFolder("data/(dis)similarities-22/MIDI_files/FS_MIDI/FS_MIDI_POLAND")
surprise_vals_hr_folder = model.getSurprisefromFolder("data/(dis)similarities-22/MIDI_files/FS_MIDI/FS_MIDI_CROATIA")

AttributeError: 'str' object has no attribute 'mean'

In [91]:
surprise, entropies, filenames = surprise_vals_pl_folder 

In [95]:
surprise

[array([ 4.7908668 ,  3.15282612,  3.67378567,  3.17284772,  3.12359156,
         3.43384157,  1.86602894,  5.45183447,  4.45040424,  5.45385434,
         4.5909777 ,  2.04894899,  2.45768375,  3.44999788,  1.5039499 ,
        10.07266943,  2.93878198,  5.58108583,  5.1135367 ,  4.02515078,
         1.81861673,  3.78228388,  8.52927482,  3.89750464,  2.3247001 ,
         4.84273255,  2.69975025,  9.24485667,  1.85785009]),
 array([4.7908668 , 3.57446284, 3.1829308 , 4.10364935, 1.9996817 ,
        5.68575301, 5.14138945, 3.79064717, 3.54169606, 3.84526651,
        4.39882388, 4.49723842, 4.11013194, 4.53566399, 3.55145113,
        4.54466263, 4.06997679, 6.29461779, 2.61717474, 5.78301843,
        4.80671851, 2.81603369, 2.79734333, 6.2081749 , 3.49762467,
        8.22610742, 5.03838402, 4.60149548, 3.68053781, 4.36221456,
        3.37849765, 7.18290345, 2.00008334, 6.19973942, 2.73601737,
        1.94499647, 1.72335538, 1.1089379 , 1.81374904]),
 array([ 4.7908668 ,  3.84642358,  2.76

In [103]:
np.concatenate(surprise).mean()

3.466565229194976

In [99]:
len(surprise)

24

In [104]:
surprise_hr, entropies_hr, filename_hr = surprise_vals_hr_folder

In [105]:
np.concatenate(surprise_hr).mean()

3.9590517335717395

In [106]:
np.concatenate(entropies).mean()

2.69660269429881

In [107]:
np.concatenate(entropies_hr).mean()

2.58199613857526